
shipping_methods:
  1: #'USA'
    attributes:
      name: 'UPS 3-5 day'
      shipping_zone_id: 1
  2: #'USA'
    attributes:
      name: 'UPS next day'
      shipping_zone_id: 1
  3: #Alaska and Hawaii
    attributes:
      name: 'UPS 3-5 day'
      shipping_zone_id: 2
  4: #Canada
    attributes:
      name: 'UPS 3-5 day'
      shipping_zone_id: 3
  5: #Canada
    attributes:
      name: 'UPS 7-14 day'
      shipping_zone_id: 3
  6: #USA Territory
    attributes:
      name: 'UPS 7-14 day'
      shipping_zone_id: 4

shipping_categories:
  1:
    attributes:
      name: Clothing
  2:
    attributes:
      name: Furniture

shipping_rates:
  1: #'FREE, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 1
      rate: 0.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 25.00
      position: 1
      active: true
  2: #'STANDARD, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 1
      rate: 7.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 0.00
      position: 2
      active: true
  3: #'EXPEDITE, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 2
      rate: 15.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 0.00
      position: 3
      active: true
  4: #'STANDARD ALASKA, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 3
      rate: 10.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 0.00
      position: 1
      active: true
  5: #'STANDARD CANADA, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 4
      rate: 15.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 0.00
      position: 1
      active: true
  6: #'GROUND CANADA, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 5
      rate: 10.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 0.00
      position: 2
      active: true
  7: #'GROUND US TERRITORY, shipping_rate_type => Order, shipping_category => Clothing'
    attributes:
      shipping_method_id: 6
      rate: 12.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 0.00
      position: 2
      active: true
  8: #'FREE, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 1
      rate: 0.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 25.00
      position: 1
      active: true
  9: #'STANDARD, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 1
      rate: 7.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 0.00
      position: 2
      active: true
  10: #'EXPEDITE, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 2
      rate: 15.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 0.00
      position: 3
      active: true
  11: #'STANDARD ALASKA, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 3
      rate: 10.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 0.00
      position: 1
      active: true
  12: #'STANDARD CANADA, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 4
      rate: 15.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 0.00
      position: 1
      active: true
  13: #'GROUND CANADA, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 5
      rate: 10.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 0.00
      position: 2
      active: true
  14: #'GROUND US TERRITORY, shipping_rate_type => Individual, shipping_category => Furniture'
    attributes:
      shipping_method_id: 6
      rate: 12.00
      shipping_rate_type_id: 1
      shipping_category_id: 2
      minimum_charge: 0.00
      position: 2
      active: true

prototypes:
  1: #Shirt
    attributes:
      name: Shirt
      active: true
  2: #Pants
    attributes:
      name: Pants
      active: true

properties:
  1: #shirt-color
    attributes:
      identifing_name: shirt-color
      display_name: color
  2: #shirt-size
    attributes:
      identifing_name: shirt-size
      display_name: size
  3: #shirt-type
    attributes:
      identifing_name: shirt-type
      display_name: type
  4: #pant-inseam
    attributes:
      identifing_name: pant-inseam
      display_name: size
  5: #pant-waist
    attributes:
      identifing_name: pant-waist
      display_name: waist
  6: #pant-color
    attributes:
      identifing_name: pant-color
      display_name: color
  7: #'pant-fit  BAGGY, SLIM'
    attributes:
      identifing_name: pant-fit
      display_name: fit

prototype_properties:
  1: #'shirt-color'
    attributes:
      property_id: 1
      prototype_id: 1
  2: #'shirt-size'
    attributes:
      property_id: 2
      prototype_id: 1
  3: #'shirt-type'
    attributes:
      property_id: 3
      prototype_id: 1
  4: #'pant-inseam'
    attributes:
      property_id: 4
      prototype_id: 2
  5: #'pant-waist'
    attributes:
      property_id: 5
      prototype_id: 2
  6: #'pant-fit'
    attributes:
      property_id: 7
      prototype_id: 2
  7: #'pant-color'
    attributes:
      property_id: 6
      prototype_id: 2

product_types:
  1: #clothes
    attributes:
      name: clothes
      parent_id:
      active: true
  2: #shirts
    attributes:
      name: shirts
      parent_id: 1
      active: true
  3:
    attributes:
      name: pants
      parent_id: 1
      active: true
brands:
  1:
    attributes:
      name: Polo
  2:
    attributes:
      name: Ralph Lauren

suppliers:
  1:
    attributes:
      name: Polo Warehouse
      email: test@test-polo.com
  2:
    attributes:
      name: RL Warehouse
      email: test@test-rl.com

tax_rates:
  1: #Clothes New York
    attributes:
      percentage: 7.0
      state_id: 1
      start_date: '2011-11-05 14:30:29'
      active: true
  2: #Luxury New York
    attributes:
      percentage: 8.0
      state_id: 38
      start_date: '2011-11-05 14:30:29'
      active: true

products:
  1: #Polo Shirt
    attributes:
      name: Cute Polo
      description: '<p>This shirt is made for developers.</p> <hr /> <p>You will love it.</p>'
      product_keywords:
        - polo
        - shirt
      brand_id: 1
      product_type_id: 2
      prototype_id: 1
      shipping_category_id: 1
      permalink: cute-polo-shirt
      available_at: '2011-11-05 14:30:29'
      deleted_at:
      meta_keywords: polo shirt
      meta_description: polo shirt for your wearing pleasure
      featured: false
      description_markup: "This shirt is made for developers.\n\n      ----------      \n\n You will love it."

  2: #Polo Pants
    attributes:
      name: Cute Pants
      description: "<p>These pants are Great.  Soft as a baby's bottom.</p> <hr /> <p>You will love them.</p>"
      product_keywords:
        - polo
        - shirt
      brand_id: 1
      product_type_id: 3
      prototype_id: 2
      shipping_category_id: 1
      permalink: cute-polo-pants
      available_at: '2011-11-05 14:30:29'
      deleted_at:
      meta_keywords: polo pants
      meta_description: polo pants for your wearing pleasure
      featured: false
      description_markup: "These pants are Great.  Soft as a baby's bottom.\n\n      ----------      \n\n You will love them."

product_properties:
  1: #'Cute Polo, COLOR'
    attributes:
      product_id: 1
      property_id: 1
      position: 1
      description: 'Red, Green, Purple'
  2: #'Cute Polo, size'
    attributes:
      product_id: 1
      property_id: 2
      position: 2
      description: 'Small, Medium, Large'
  3: #'Cute Polo, type'
    attributes:
      product_id: 1
      property_id: 3
      position: 3
      description: 'Golf Shirt'
  4: #'Cute Pants, COLOR'
    attributes:
      product_id: 2
      property_id: 6
      position: 1
      description: 'Blue, Black, Grey'
  5: #'Cute Pants, inseam'
    attributes:
      product_id: 2
      property_id: 4
      position: 2
      description: '30in, 32in, 34in'
  6: #'Cute Pants, waist'
    attributes:
      product_id: 2
      property_id: 5
      position: 3
      description: '32in, 34in, 36in'
  7: #'Cute Pants, fit'
    attributes:
      product_id: 2
      property_id: 7
      position: 3
      description: 'Baggy, Slim'

inventories:
  1:
    attributes:
      count_on_hand: 11
      count_pending_to_customer: 5
      count_pending_from_supplier: 0
  2:
    attributes:
      count_on_hand: 102
      count_pending_to_customer: 0
      count_pending_from_supplier: 0
  3:
    attributes:
      count_on_hand: 103
      count_pending_to_customer: 0
      count_pending_from_supplier: 0
  4:
    attributes:
      count_on_hand: 104
      count_pending_to_customer: 0
      count_pending_from_supplier: 0
  5:
    attributes:
      count_on_hand: 105
      count_pending_to_customer: 0
      count_pending_from_supplier: 0
variants:
  1: #'Polo Shirt 1'
    attributes:
      product_id: 1
      sku: 0000-0000-000001
      name:
      price: 30.00
      cost: 10.00
      inventory_id: 1
  2: #'Polo Shirt 2'
    attributes:
      product_id: 1
      sku: 0000-0000-000002
      name:
      price: 30.00
      cost: 10.00
      inventory_id: 2
  3: #'Polo Shirt 3'
    attributes:
      product_id: 1
      sku: 0000-0000-000003
      name:
      price: 30.00
      cost: 10.00
      inventory_id: 3
  4: #'Cute Pants 1'
    attributes:
      product_id: 2
      sku: 0000-0001-000001
      name:
      price: 30.00
      cost: 10.00
      inventory_id: 4
  5: #'Cute Pants 2'
    attributes:
      product_id: 2
      sku: 0000-0001-000002
      name:
      price: 30.00
      cost: 10.00
      inventory_id: 5
variant_properties:
  1: #'Polo Shirt 1'
    attributes:
      variant_id: 1
      property_id: 1
      description: Red
      primary: 1
  2: #'Polo Shirt 2'
    attributes:
      variant_id: 2
      property_id: 1
      description: Green
      primary: 1
  3: #'Polo Shirt 1'
    attributes:
      variant_id: 1
      property_id: 2
      description: Small
      primary: 0
  4: #'Polo Shirt 2'
    attributes:
      variant_id: 2
      property_id: 2
      description: Medium
      primary: 0
  5: #'Polo Shirt 3'
    attributes:
      variant_id: 3
      property_id: 2
      description: Small
      primary: 0
  6: #'Polo Shirt 3'
    attributes:
      variant_id: 3
      property_id: 1
      description: Purple
      primary: 0
  7: #'Cute Pants 1'
    attributes:
      variant_id: 4
      property_id: 6
      description: Blue
      primary: 1
  8: #'Cute Pants 1 inseam'
    attributes:
      variant_id: 4
      property_id: 4
      description: 30in
      primary: 0
  9: #'Cute Pants 1 waist'
    attributes:
      variant_id: 4
      property_id: 5
      description: 34in
      primary: 0
  10: #'Cute Pants 1 fit'
    attributes:
      variant_id: 4
      property_id: 7
      description: Slim
      primary: 0
  11: #'Cute Pants 1'
    attributes:
      variant_id: 5
      property_id: 6
      description: Black
      primary: 1
  12: #'Cute Pants 1 inseam'
    attributes:
      variant_id: 5
      property_id: 4
      description: 32in
      primary: 0
  13: #'Cute Pants 1 waist'
    attributes:
      variant_id: 5
      property_id: 5
      description: 32in
      primary: 0
  14: #'Cute Pants 1 fit'
    attributes:
      variant_id: 5
      property_id: 7
      description: Baggy
      primary: 0

variant_suppliers:
  1:
    attributes:
      variant_id: 1
      supplier_id: 1
      cost: 10.00
      total_quantity_supplied: 0
      min_quantity: 11
      max_quantity: 1001
      active: true
  2:
    attributes:
      variant_id: 2
      supplier_id: 1
      cost: 10.00
      total_quantity_supplied: 0
      min_quantity: 12
      max_quantity: 1002
      active: true
  3:
    attributes:
      variant_id: 3
      supplier_id: 1
      cost: 10.00
      total_quantity_supplied: 0
      min_quantity: 13
      max_quantity: 1003
      active: true
  4:
    attributes:
      variant_id: 4
      supplier_id: 2
      cost: 15.00
      total_quantity_supplied: 0
      min_quantity: 4
      max_quantity: 400
      active: true
  5:
    attributes:
      variant_id: 5
      supplier_id: 2
      cost: 15.00
      total_quantity_supplied: 0
      min_quantity: 5
      max_quantity: 500
      active: true
